[package]
name = "rustls-openssl"
authors = ["Tom Fay <tom@teamfay.co.uk>"]
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Rustls crypto provider for OpenSSL"
homepage = "https://github.com/tofay/rustls-openssl"
repository = "https://github.com/tofay/rustls-openssl"
readme = "README.md"

[dependencies]
openssl = { version = "0.10.68" }
rustls = { version = "0.23.0", features = [
    "tls12",
    "std",
], default-features = false }
rustls-webpki = "0.102.2"

[features]
default = []
x25519 = []
chacha = []

[dev-dependencies]
lazy_static = "1.4.0"
once_cell = "1.8.0"
rstest = "0.23.0"
rustls-pemfile = "2"
webpki-roots = "0.26"
