[package]
name = "rustls-openssl"
authors = ["Tom Fay <tom@teamfay.co.uk>"]
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "Rustls crypto provider for OpenSSL"
homepage = "https://github.com/tofay/rustls-openssl"
repository = "https://github.com/tofay/rustls-openssl"
readme = "README.md"

[dependencies]
foreign-types-shared = { version = "0.1.1", optional = true }
openssl = "0.10.68"
openssl-sys = "0.9.104"
rustls = { version = "0.23.0", default-features = false }
rustls-webpki = { version = "0.102.2", default-features = false }
once_cell = "1.8.0"

[features]
default = ["tls12"]
fips = []
tls12 = ["rustls/tls12", "foreign-types-shared"]

[dev-dependencies]
hex = "0.4.3"
rcgen = { version = "0.13.1", default-features = false, features = [
    "aws_lc_rs",
] }
rstest = "0.23.0"
# Use aws_lc_rs to test our provider
rustls = { version = "0.23.0", features = ["aws_lc_rs"] }
rustls-pemfile = "2"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
webpki-roots = "0.26"
